# Generated by Django 4.0.4 on 2022-04-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_book_status_book_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicalsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_number', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publishinghouse')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodicals.periodicalstype')),
            ],
        ),
    ]
